### ISSUE TITLE
Flush() doesn't upload all cached files data

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#109]
There are some old and history event data in the cache folder
C:\Users\myuser\AppData\Local\segment.data.

It will only upload the latest generated cached file when Flush() is called.
The old file data would not be uploaded.

For instance, the two files are generated before. but it's not uploaded when Flush() is called.
![1727165687060](https://github.com/user-attachments/assets/789196a6-979e-4907-817e-9d288d3dbb15)

Also, one question from this:
How does Flush() work?

It doesn't scan the cached folder according to the source code?

https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Analytics.cs

```
public virtual void Flush() => Apply(plugin =>
{
    if (plugin is EventPlugin eventPlugin)
    {
        eventPlugin.Flush();
    }
});
```

**Comment by wenxi-zeng** [comment]
@arlyxiao, the flush does scan the cached folder, but only look for the files with an extension (see [here](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Utilities/Storage.cs#L316)). the ones that do not have extension are temporary files. the SDK first writes events to a temporary file that has no extension, and rolls over to another temporary file when finish. the previous file is then closed with an extension name (see [here](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Utilities/Storage.cs#L440)).

the files in the screenshots likely are generated by previous tests. install/uninstall apps may cause this issue, since the SDK lost the track of the files. you can customize the behavior to clean up all files by providing your own storage implementation (see [here](https://github.com/segmentio/Analytics-CSharp/tree/main?tab=readme-ov-file#customize-storage))
