### ISSUE TITLE
Null Reference Error When Using RawEvent in Hangfire-Scheduled _analytics.Track Call

### ISSUE THREAD

**Issue by RaviAajugiya** [segmentio/Analytics-CSharp#114]
**Describe the bug**
When scheduling a Hangfire job to call _analytics.Track with a RawEvent delegate, RawEvent is found to be null, resulting in a NullReferenceException. This issue does not occur when _analytics.Track is called directly, without scheduling through Hangfire, suggesting a discrepancy in how RawEvent is instantiated or accessed within Hangfire's execution context.

**To Reproduce**
1. Schedule ScheduleIntegrationTrialExpiringTomorrow as a background job using Hangfire.
2. Within ScheduleIntegrationTrialExpiringTomorrow, attempt to use _analytics.Track with a delegate that modifies RawEvent.
```csharp
public class HangfireService : IHangfireService
{
    private readonly Analytics _analytics;

    // Constructor that injects an Analytics instance
    public HangfireService(Analytics analytics)
    {
        _analytics = analytics;
    }

    // Method to schedule a Hangfire job that will run after a delay
    public void ScheduleIntegrationTrialJob()
    {
        // Creating a DTO with integration details to pass to the scheduled job
        var integrationDetail = new SegmentIntegrationDetailDto
        {
            CompanyIdentifier = "Company123",
            IntegrationCustomName = "Marketing Integration",
            IntegrationGuideUrl = "https://company.com/guide",
            IntegrationMessage = "Welcome to the integration",
            IntegrationName = "HubSpot Integration",
            IntegrationType = "CRM"
        };

        // Scheduling the job to run after 60 seconds
        BackgroundJob.Schedule<HangfireService>(
            x => this.ScheduleIntegrationTrialExpiringTomorrow(integrationDetail), 
            TimeSpan.FromSeconds(60)
        );
    }

    // Method called by Hangfire to track an integration trial expiring event
    public void ScheduleIntegrationTrialExpiringTomorrow(SegmentIntegrationDetailDto integrationDetail)
    {
        // First call to _analytics.Track without a RawEvent delegate - this works as expected
        _analytics.Track("integration_trial_expiring_tomorrow", integrationDetail);

        // Second call to _analytics.Track with a RawEvent delegate - this causes a NullReferenceException
        // when scheduled through Hangfire, as RawEvent is null. However, this same call works 
        // without issues when executed directly (not through Hangfire).
        _analytics.Track("integration_trial_expiring_tomorrow", integrationDetail, RawEvent =>
        {
            RawEvent.UserId = "123";  // Attempting to set the UserId, but RawEvent is null in this context
            return RawEvent;
        });
    }
}
```

**Expected behavior**
When scheduled as a background job, the RawEvent parameter is null, causing a NullReferenceException. Calling _analytics.Track directly without scheduling works as expected, even with the RawEvent delegate.

**Comment by wenxi-zeng** [comment]
hey @RaviAajugiya, the first call works as expected because the enrichment closure/delegate is null (see [this line](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Timeline.cs#L39)). the second call passes a closure/delegate and that closure/delegate is invoked with the enrichment result from previous plugins (see [this line](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Timeline.cs#L38)). I'd suggest to check if you have any plugins that returns null after processing. 

if you don't have any custom plugins, there are 2 cases you might receive null values in the closure/delegate:
* you have a destination plugin but it's not enabled (see [this line](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Plugins.cs#L148))
* analytics is not ready (see [this line](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Plugins/StartupQueue.cs#L39)). this happens when analytics failed to fetch settings from network, or there are events being tracked before analytics got settings

in either case, you should do null checks yourself to prevent NullReferenceException
