### ISSUE TITLE
Double check the bug: temporary file is not generated

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#121]
I know this is duplicated issues. But it happens in my local.
Previous detail: https://github.com/segmentio/Analytics-CSharp/issues/120

SDK version: 2.4.2
windows: dotnet framework 4.7.2

The steps below:

1. Close network
2. Create new segment instance with write key offline via the default config. Just pass the write key to the constructor function.
3. Generate group events offline.

Note: I tried with default and use a full new hello world app to test.
Please try the steps above under invalid network with full new app. It will happen.

**Comment by wenxi-zeng** [comment]
@arlyxiao thanks for the details. that's helpful to understand the problem. how long did you wait for the file to be generated before you kill the app?

analytics needs to fetch settings from backend during initialization. if the network is turned off before initialization, then analytics won't be able to get the settings and will wait for http client to time out and then fallback to use cached settings. all events are cached in memory during this step and will be replayed once settings comes back. if you kill the app before that, all events are lost. this is expected behavior since the app is killed before the SDK is ready.

you can follow the [example](https://github.com/segmentio/Analytics-CSharp?tab=readme-ov-file#listen-to-analytics-logs) to enable logging and check if [this log](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/Plugins/StartupQueue.cs#L47) is outputted to make sure analytics is ready. if you do not see files generated when analytics is ready. feel free to reopen this issue.
