### ISSUE TITLE
Page method?

### ISSUE THREAD

**Issue by gfody** [segmentio/Analytics-CSharp#24]
Trying to upgrade from [Analytics.NET](https://github.com/segmentio/Analytics.NET) but this method appears to be missing

**Comment by wenxi-zeng** [comment]
hey @gfody can you be specific which method is missing? seems like you forgot to link the method

**Comment by gfody** [comment]
the page method, [here in the docs](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#page) and [here in Analytics.NET](https://github.com/segmentio/Analytics.NET/blob/master/Analytics/Client.cs#L221-L265), is there an equivalent in Analytics-CSharp?

**Comment by wenxi-zeng** [comment]
sorry, I didn't read the title 😅. 
yes, there is a `screen` call that's equivalent to `page` (see screen doc [here](https://segment.com/docs/connections/spec/screen/)). the difference is that `screen` is meant for mobile device, and `page` is meant for webpages. `screen` might have more context (device info, etc), but they serve the same purpose. 
can you please elaborate more about your use case? we want to understand the circumstances where a server lib needs to track a frontend page before we introduce a new api. thanks!

**Comment by gfody** [comment]
I'm not very familiar with this library. We're trying to migrate legacy code from legacy .NET to dotnetcore and along the way had to switch from Analytics.NET to Analytics-CSharp as only the latter supports netstandard2.0 - the only context I have is that this call to the `Page` method has this comment:
```cs
            // Send Page event (as needed)
            // Note: This is for Google Analytics Pageviews
```
(this is nestled deep in some helper class that's ultimately invoked from ASP.NET controller methods)

I see that the legacy library contains both `Client.Screen` as well as `Client.Page` are these safely interchangeable?

**Comment by wenxi-zeng** [comment]
@gfody thanks for the additional info. that's very helpful. our team is planning to add support for a `page` method, since this library is going to support not just the mobile platform. in the meanwhile, there are two walk arounds that you can try:

**approach 1: update mappings in your segment workspace:**
1. go to your segment.com workspace
2. go to `Connections`
3. go to  `Destinations`
4. choose your Google Analytics destination
5. click mappings on the tab
6. click `Page View` if it exists. otherwise click new mapping and choose `Page View`
7. under `Select events to map and send`, update `Event Type is Page` to be `Event Type is screen`
8. save the mapping

**approach 2: write a plugin to update the event type**
1. add this plugin to your project:
```
class PagePlguin : EventPlugin
{
    public override PluginType type => PluginType.Before;

    public override ScreenEvent Screen(ScreenEvent screenEvent)
    {
        screenEvent.type = "page";
        return base.Screen(screenEvent);
    }
}
```
2. add the plugin to your analytics
```
analytics.Add(new PagePlguin());
```
3. now all the `screen` events have a type `page`. this should make segment server recognize it as a `page` event and forward it correctly to your Google Analytics as Pageviews.

I'm going to mark this issue as closed for now. I'll update the status when we have the `page` method added. feel free to reopen this ticket, if the suggested walk around does not work. thanks!
