### ISSUE TITLE
Segment writeKey exposed in request data and filename

### ISSUE THREAD

**Issue by al2114** [segmentio/Analytics-CSharp#69]
Default storage provider saves writeKeys in its file structure

https://github.com/segmentio/Analytics-CSharp/blob/eab258655543263d27234b9ef86fbb5a6e1d997a/Analytics-CSharp/Segment/Analytics/Utilities/Storage.cs#L133C1-L134C1

This can expose the key to other libraries with access to app sandbox.

In addition, we noticed `writeKey` getting exposed as part of request body data similar to this issue that had been fixed in the .NET library

https://github.com/segmentio/Analytics.NET/issues/98

These all get exposed with logging enabled

**Comment by wenxi-zeng** [comment]
hey @al2114, please find following
1. writeKey is not a secret. see these similar questions [here](https://github.com/segmentio/analytics-php/issues/127) and [here](https://github.com/segmentio/analytics.js/issues/613).
2. segment logs should be turned off in production. segment has changed the implementation that requires a writeKey in the payload body. so that's something can't change.

what you can do to fit your use case:
1. write your own `StorageProvider` (copy/paste the default one and change the file path with no writeKey)
2. turn off segment logs in production

**Comment by paolo-aquino-ml** [comment]
Adding more references related to this matter since the older referenced link was already archived and normally presented as a top search result. Hopefully links below would add some depth on how customers should think about this:
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/faq/#what-is-the-impact-of-exposing-the-sources-write-keys

https://community.segment.com/product-q-a-66/how-to-track-cli-usage-and-protect-write-key-335
