### ISSUE TITLE
Add support for synchronously flush

### ISSUE THREAD

**Issue by jn011** [segmentio/Analytics-CSharp#74]
Hi there,

I have recently tried to integrate with the new library in my serverless function which runs on .NET 6. 

In [Analytics.NET](https://github.com/segmentio/Analytics.NET) a call to `Flush()` would block the current thread and upload all events in the queue for a given client to Segment.

In Analytics-CSharp it seems that flush **does not** force upload events to segment?
Please checkout my reproduction code below and let me know if my usage is incorrect, in the old client this exact flow works perfectly. For this reason I have continued using Analytics .NET in my project for now.

```csharp
using Segment.Analytics;
using Segment.Analytics.Utilities;

class SegmentLogger : ISegmentLogger
{
    public void Log(LogLevel logLevel, Exception exception = null, string message = null)
    {
        switch (logLevel)
        {
            case LogLevel.Warning:
            case LogLevel.Information:
            case LogLevel.Debug:
                Console.Out.WriteLine("Message: " + message);
                break;
            case LogLevel.Critical:
            case LogLevel.Trace:
            case LogLevel.Error:
                Console.Error.WriteLine("Exception: " + exception?.StackTrace);
                Console.Error.WriteLine("Message: " + message);
                break;
            case LogLevel.None:
            default:
                break;
        }
    }
}

internal class Program
{
    public static void Main(string[] args)
    {
        Analytics.Logger = new SegmentLogger();

        var analytics = new Analytics(new Configuration("__OMITTED__", storageProvider: new InMemoryStorageProvider()));

        var properties = new Dictionary<string, object?>
        {
            { "TesterProperty", "12345!" },
        };
    

        analytics.Track("dummy_event", properties);

        // Issue, flush does not upload to segment synchronously as expected
        analytics.Flush();
    }
}
```

Thanks!

**Comment by wenxi-zeng** [comment]
hey @jn011, that is correct. analytics-csharp does not block and wait for flush to be completed. it is designed to work in a fire-and-forget manner to achieve higher throughputs. by explicitly calling `Analytics.Flush()` it merely sends a flush signal to the worker thread, and worker thread will do the job according to it's schedule.

you can always write your own plugin to make uploads synchronous, but it's not an easy job and strongly discouraged since it will degrade the performance of your app.

could you please provide more context about your use case of needing a sync flush? I can file a feature request if it feels necessary. thanks!

**Comment by jn011** [comment]
Hey @wenxi-zeng interesting, thanks for sharing. 

For my use case I want flush to be synchronous not all uploads explicitly. 

This is how my flow looks:
1. Serverless function receives x amount of events from an event stream which need to be transformed and tracked in segment
2. For each of these events they go through a pipeline which calls Analytics.Track 1 to many times. 
3. After this pipeline finishes we need to ensure that the serverless function has uploaded all the events to segment, my intention is to force this by calling Analytics.Flush. If we don't ensure that all events are uploaded then the serverless function can exit with unsent items still inside the background queue and lost forever.

**Comment by wenxi-zeng** [comment]
hey @jn011, thanks for the additional detail. this is a valid use case. probably very common for server use cases. so we will add support to it.

**Comment by jn011** [comment]
Thanks @wenxi-zeng

Please let me know when this is done. It's the missing piece in order of us to migrate to the new API. 

Have you got an extensive list of what's improved from Analytics.NET anywhere?

**Comment by wenxi-zeng** [comment]
@jn011 we don't have a list yet. but performance-wise, you can take a look at this [blog](https://segment.com/blog/sdk-performance-improvements/) that we benchmarked the old and new android/ios sdks. analytics-csharp implements the same architecture. we do have a plan to write another blog for this c# library.

feature-wise:
* as you might have been noticed, this library is a lot more flexible and extensible than the old one. 
* you can write plugins to enrich data, to drop off data, to direct the data to a different server, etc. 
* you can customize your storage, httpclient, etc. 
* you can write your own flush policy to decide when and how to flush data. 
* you can choose your preferred json library (Json.NET or System.Text.Json) by targeting .netstandard 1.3 or 2.0, avoiding to have both json library in your app, reduces the size. 
* this library is also cross-platform. it works the same across .NET, Xamarin, and Unity

**Comment by MichaelGHSeg** [comment]
Closed in error, this is still in progress. Sorry!

**Comment by jn011** [comment]
Hi @wenxi-zeng Any updates on this?

**Comment by jn011** [comment]
Thanks, any further news?

**Comment by MichaelGHSeg** [comment]
There's a new release that should address this issue.  There is now an option to specify an EventPipelineProvider on the Analytics configuration object.  Setting it with a new SyncEventPipeline will use a synchronous flush method.  Sorry for the delay in getting this out, we had a couple false starts and distractions.

Let us know how it works for you!

**Comment by AdamPD** [comment]
@MichaelGHSeg - this wasn't done correctly.  The constructor of `Configuratin` takes an `EventPipelineProvider` instead of `IEventPipelineProvider`.  `SyncEventPipelineProvider` doesn't inherit from `EventPipelineProvider` so basically this can't be used.

**Comment by AdamPD** [comment]
Moreover, the implementation is poor anyway.  The `Write()` seems to still using asynchronous channels to record the events to storage, so if you write and then immediately `Flush()`, your events haven't even been written to disk yet, so `Flush()` does nothing.

It honestly seems terribly over-engineered for something as simple as writing events to an HTTP channel.  All of the asynchronous code should be **opt in** not **opt out**.  At a basic level, when you write an event, it should write it immediately and synchronously.

**Comment by AdamPD** [comment]
@wenxi-zeng thanks for the reply.

I understand your points, but I would venture a good guess that .NET is primarily used for the server use case.  Yes - I accept there is Unity/Xamarin/etc., but I'm sure .NET is primarily used on the "server."

In our use case, for example, we're using AWS Lambda functions for REST API calls to .NET, meaning async is absoutely not an option (or we'll certainly lose events).

If you accept that .NET is primarily used server-side, and given the industry shift towards short-lived scale up/down instances (either serverless or container-based), then having async by default is the wrong decision.

I would go as far as to say that the library should, by default, send events synchronously (without the need for a flush), and you can progressively opt-in to an asynchronous store/flush model as required.

I did fork and modify the source to use IEventPipelineProvider, and did try the in-memory storage provider, but because the `Write()` is still via a channel, and there are no semaphores to enable synchronous writes, there are still race conditions meaning I may lose events (i.e. the Write running on another thread commits the event to memory after the Flush operation gets the in-memory events to upload).

Ultimately, this was far too time consuming and risky, so we had to go backwards to the legacy Analytics package.

That's really disappointing, because I really believe my use case would be the primary use case for this package, and it's treated like an edge case, making the package unviable.

**Comment by AdamPD** [comment]
@wenxi-zeng just looping back on this one again.

I understand what you're describing, but you're describing use cases that are seamingly edge cases.  Basically, by default, this library can't be used for any transient serverless frameworks, because you can't guarantee writes.  That means, there is no .NET server-side library that you can use to reliably write events in a serverless environment.

It doesn't make much sense to me to state that's because you want to "support cross-platform."  You can easily support cross-platform by making async write/flush **opt in** rather than the default.  The documentation could make this very clear that if you have a "highly intensive dataflow", you can opt in to an async write/flush pipeline.

I will test now that `Configuration` is using `IEventPipelineProvider` in its constructor and see if I can find a way to do this.
