### ISSUE TITLE
FlushAt is not working for values > 1

### ISSUE THREAD

**Issue by Shield-Jaguar** [segmentio/Analytics-CSharp#81]
**Describe the bug**
The value of `flushAt` other than 1 is not working

**To Reproduce**
1. Open mvc sample
2. Change the value of flush at to 5

**Expected behavior**
After 5 events the value should appear on segment source debugger but only first track event appears

**Screenshots**
(Only 1 event appear)
![image](https://github.com/segmentio/Analytics-CSharp/assets/37825767/f3410409-2cdb-499f-badb-f38709aaa607)

**Platform (please complete the following information):**
 - Library Version in use: [e.g. 0.0.5]
 - Platform being tested: [.net core on macOS]
 - Integrations in use: [Mixpanel]

**Additional context**
Log file attached. 6 pizas added, and all of them deleted. but only one event appears. If we set that `flushAt` value in configuration to 1, all events can be observed in source debugger. 
[Segment.log](https://github.com/segmentio/Analytics-CSharp/files/13659899/Segment.log)

**Comment by wenxi-zeng** [comment]
hey @Shield-Jaguar thanks for reporting this issue. can you provide a sample code of how you setup the analytics? are you using analytics as a singleton? also which version are you using? 
looks like you are using in-memory storage and analytics is scoped to every page, if that's the case, I can see it happening. if the webpage getting killed when the event is being flushed, the rest of the events are lost because of they are stored in memory and scoped to the page. try set analytics as a singleton, see if the issue still persists. I don see a serialization exception in the log you provided, I'm going to take a look and have it fixed, but it should not causing event lost

**Comment by Shield-Jaguar** [comment]
@wenxi-zeng here is the [sample code](https://github.com/Shield-Jaguar/SegmentSample) to reproduce the issue 

 > Are you using analytics as a singleton?

No, I am registering the dependency as [scoped](https://github.com/Shield-Jaguar/SegmentSample/blob/b9d7b3d13908e019b46a07e15f086562e8987a66/AspNetMvcSample/Startup.cs#L32)

> which version are you using

.NET 8, Library [2.3.1](https://github.com/Shield-Jaguar/SegmentSample/blob/b9d7b3d13908e019b46a07e15f086562e8987a66/AspNetMvcSample/AspNetMvcSample.csproj#L9)

We cannot register segment library as Singleton, because we want to send `identify` call and then `track` call.  

Let me know if you need more details.

**Comment by Shield-Jaguar** [comment]
@wenxi-zeng any update on this?

**Comment by wenxi-zeng** [comment]
hey @Shield-Jaguar sorry for the delay. I'm looking into this today. but I don't think it's possible to stay scoped, in-memory and not flush at a per event basis while guarantee no data loss. the logic is simple: events are hold in-memory and not flush immediately, if the webpage gets closed/redirected, new analytics instance created for the new page, the old one of previous page deconstructed along with the events in memory. 

the conditions below cannot all be true at the same time, at least one of them should be false:
* scoped
* in-memory
* not flush at a per event basis

**Comment by wenxi-zeng** [comment]
@Shield-Jaguar I have verified that flushAt works properly for values > 1 (you can verify this by tracking `n` times before `RedirectToAction` is called, where `n` is the value of flushAt). 

the issue that you encounter is just what I described in my previous comment (you can verify this by setting breakpoint at the constructor of `AnalyticsController`. you will see the instance of analytics gets overwritten for every redirection).

that being said, if you want to stay completely stateless, you will have to flush at a per event basis, since the sdk won't know when is a redirection gonna happen. 

alternatively you can manually flush before the redirection happens, but this requires synchronously flush mentioned in #74. however, even this feature is available, I don't suggest of doing it, because it might freeze your webpage during redirection. 

closing this issue out since it's not a sdk problem, more about trade-offs of doing things in the app.

**Comment by wenxi-zeng** [comment]
regarding to the exception in the log, it's reported by Segment logger for debugging purpose. it is handled properly and ignored inside the sdk.

**Comment by Shield-Jaguar** [comment]
@wenxi-zeng It appears that the SDK isn't compatible with server applications, as I'm unable to register it as scoped. This aspect of the SDK's design feels flawed, especially concerning the inability to set the userId for concurrent calls.

To link tracking events to a user, I must call the `_analytics.Identify("userId")` method. However, if `_analytics` is registered as a singleton, this means that the userId is shared across concurrent calls, while each call should ideally have its own userId. Even attempting to use the track call proves futile in server applications.

Consider the scenario outlined in the code snippet below. I cannot attach the userId to this call in a server application. The current implementation seems suitable for desktop or client applications, where tracking a single user at a time is more common.

```csharp
_analytics.Track($"VSCodeExtension_{eventName}", new JsonObject
{
    ["userId"] =  "someUserId"
    ["Data"] =  "someData"
});

Moreover, there's no provision to set the userId in the track call since the _userInfo property is marked as internal. This limitation further impedes the flexibility and usability of the SDK in server environments.

**Comment by wenxi-zeng** [comment]
hi @Shield-Jaguar, you can write a plugin to attach userId at a per event basis. please see this [comment](https://github.com/segmentio/Analytics-CSharp/issues/75#issuecomment-1768701914) for details.
